const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const els = {
  start: $('#startPanel'), send: $('#sendPanel'), receive: $('#receivePanel'), transfer: $('#transferPanel'),
  file: $('#fileInput'), drop: $('#dropzone'), dropTitle: $('#dropTitle'), dropHint: $('#dropHint'), offerArea: $('#offerArea'),
  offerCode: $('#offerCode'), offerQr: $('#offerQr'), offerSize: $('#offerSize'), answerInput: $('#answerInput'),
  offerInput: $('#offerInput'), answerArea: $('#answerArea'), answerCode: $('#answerCode'), answerQr: $('#answerQr'), answerSize: $('#answerSize'),
  state: $('#connectionState'), transferTitle: $('#transferTitle'), transferMeta: $('#transferMeta'), progress: $('#progressBar'), progressText: $('#progressText'), bytesText: $('#bytesText'), speedText: $('#speedText'), result: $('#resultArea'), orb: $('#statusOrb'),
  scanner: $('#scannerDialog'), scannerVideo: $('#scannerVideo'), scannerHelp: $('#scannerHelp'), toast: $('#toast')
};

let pc, channel, selectedFile, receiveMeta, receiveChunks = [], receivedBytes = 0, sentBytes = 0, transferStarted = 0, scannerStream, scanTimer;
const ICE = [{ urls: 'stun:stun.l.google.com:19302' }, { urls: 'stun:stun1.l.google.com:19302' }];
const CHUNK = 64 * 1024;

function toast(msg){ els.toast.textContent = msg; els.toast.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>els.toast.classList.remove('show'),1800); }
function show(panel){ [els.start,els.send,els.receive,els.transfer].forEach(x=>x.classList.add('hidden')); panel.classList.remove('hidden'); window.scrollTo({top:panel.offsetTop-20,behavior:'smooth'}); }
function formatBytes(n=0){ if(!n) return '0 B'; const u=['B','KB','MB','GB','TB']; const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1); return `${(n/1024**i).toFixed(i?1:0)} ${u[i]}`; }
function base64url(bytes){ let s=''; for(const b of bytes)s+=String.fromCharCode(b); return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''); }
function fromBase64url(s){ s=s.replaceAll('-','+').replaceAll('_','/'); while(s.length%4)s+='='; const bin=atob(s), out=new Uint8Array(bin.length); for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i); return out; }
async function encodeSignal(obj){ const raw=new TextEncoder().encode(JSON.stringify(obj)); if('CompressionStream' in window){ const cs=new CompressionStream('gzip'); const ab=await new Response(new Blob([raw]).stream().pipeThrough(cs)).arrayBuffer(); return 'EN1.'+base64url(new Uint8Array(ab)); } return 'EN0.'+base64url(raw); }
async function decodeSignal(code){ const [prefix,data]=code.trim().split('.',2); if(!data) throw new Error('Código inválido'); const bytes=fromBase64url(data); let raw=bytes; if(prefix==='EN1'){ if(!('DecompressionStream' in window)) throw new Error('Este navegador não consegue descompactar o convite.'); const ds=new DecompressionStream('gzip'); raw=new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer()); } return JSON.parse(new TextDecoder().decode(raw)); }
async function sha256Blob(blob){ const hash=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()); return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
function waitIce(peer){ if(peer.iceGatheringState==='complete') return Promise.resolve(); return new Promise(resolve=>{ const fn=()=>{ if(peer.iceGatheringState==='complete'){peer.removeEventListener('icegatheringstatechange',fn);resolve();}}; peer.addEventListener('icegatheringstatechange',fn); setTimeout(resolve,7000); }); }
function makePeer(){ if(pc) pc.close(); pc=new RTCPeerConnection({iceServers:ICE}); pc.onconnectionstatechange=()=>{ const s=pc.connectionState; els.state.textContent=s.toUpperCase(); if(s==='connected'){ els.orb.textContent='✓'; els.transferTitle.textContent=channel?.readyState==='open'?'Canal direto conectado':'Conectado ao outro dispositivo'; } if(['failed','disconnected','closed'].includes(s)){els.orb.textContent='!';} }; pc.ondatachannel=e=>setupChannel(e.channel,false); return pc; }
function renderQR(el,text){ el.innerHTML=''; if(window.QRCode){ try{ new QRCode(el,{text,width:180,height:180,correctLevel:QRCode.CorrectLevel.L}); }catch{ el.innerHTML='<small style="color:#111;text-align:center">QR grande demais.<br>Use o código ao lado.</small>'; } } else el.innerHTML='<small style="color:#111;text-align:center">QR indisponível.<br>Use o código ao lado.</small>'; }
function updateTransfer(done,total){ const pct=total?Math.min(100,done/total*100):0; els.progress.style.width=pct+'%'; els.progressText.textContent=pct.toFixed(1)+'%'; els.bytesText.textContent=`${formatBytes(done)} / ${formatBytes(total)}`; const sec=(performance.now()-transferStarted)/1000; els.speedText.textContent=sec>.25?`${formatBytes(done/sec)}/s`:'—'; }
function setupChannel(ch,isSender){ channel=ch; channel.binaryType='arraybuffer'; channel.bufferedAmountLowThreshold=512*1024; channel.onopen=()=>{ show(els.transfer); els.state.textContent='CONECTADO'; els.orb.textContent='✓'; if(isSender){ els.transferTitle.textContent='Enviando direto…'; els.transferMeta.textContent=selectedFile?`${selectedFile.name} · ${formatBytes(selectedFile.size)}`:''; sendFile(); } else { els.transferTitle.textContent='Canal pronto para receber'; els.transferMeta.textContent='Aguardando metadados do arquivo…'; } }; channel.onclose=()=>els.state.textContent='CANAL FECHADO'; channel.onerror=()=>toast('Falha no canal P2P'); channel.onmessage=onMessage; }
async function sendFile(){ if(!selectedFile||!channel||channel.readyState!=='open')return; sentBytes=0;transferStarted=performance.now();els.result.classList.add('hidden'); const hash=await sha256Blob(selectedFile); channel.send(JSON.stringify({type:'meta',name:selectedFile.name,size:selectedFile.size,mime:selectedFile.type||'application/octet-stream',sha256:hash})); for(let off=0;off<selectedFile.size;off+=CHUNK){ while(channel.bufferedAmount>2*1024*1024) await new Promise(r=>{const fn=()=>{channel.removeEventListener('bufferedamountlow',fn);r();};channel.addEventListener('bufferedamountlow',fn,{once:true});setTimeout(fn,500);}); const buf=await selectedFile.slice(off,Math.min(off+CHUNK,selectedFile.size)).arrayBuffer(); channel.send(buf); sentBytes+=buf.byteLength; updateTransfer(sentBytes,selectedFile.size); } channel.send(JSON.stringify({type:'done'})); els.transferTitle.textContent='Arquivo enviado'; els.result.innerHTML=`<strong>Transferência concluída.</strong><p class="muted">SHA-256: <code>${hash}</code></p>`;els.result.classList.remove('hidden'); }
async function onMessage(ev){ if(typeof ev.data==='string'){ const msg=JSON.parse(ev.data); if(msg.type==='meta'){ receiveMeta=msg;receiveChunks=[];receivedBytes=0;transferStarted=performance.now();els.transferTitle.textContent=`Recebendo ${msg.name}`;els.transferMeta.textContent=`${formatBytes(msg.size)} · verificação SHA-256 ao final`;updateTransfer(0,msg.size); } else if(msg.type==='done'){ await finishReceive(); } return; } receiveChunks.push(ev.data);receivedBytes+=ev.data.byteLength;updateTransfer(receivedBytes,receiveMeta?.size||receivedBytes); }
async function finishReceive(){ const blob=new Blob(receiveChunks,{type:receiveMeta.mime}); const hash=await sha256Blob(blob); const ok=hash===receiveMeta.sha256; const url=URL.createObjectURL(blob); els.transferTitle.textContent=ok?'Arquivo recebido e verificado':'Arquivo recebido com divergência'; els.orb.textContent=ok?'✓':'!'; els.result.innerHTML=`<strong>${ok?'Integridade confirmada':'Hash não confere'}</strong><p class="muted">${receiveMeta.name} · ${formatBytes(blob.size)}<br>SHA-256: <code>${hash}</code></p>${ok?`<a download="${escapeHtml(receiveMeta.name)}" href="${url}">Salvar arquivo</a>`:''}`;els.result.classList.remove('hidden'); updateTransfer(receiveMeta.size,receiveMeta.size); }
function escapeHtml(s){return s.replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
async function createOffer(){ if(!selectedFile)return; const peer=makePeer(); setupChannel(peer.createDataChannel('entrenos',{ordered:true}),true); await peer.setLocalDescription(await peer.createOffer()); await waitIce(peer); const code=await encodeSignal(peer.localDescription.toJSON()); els.offerCode.value=code; els.offerSize.textContent=`${code.length} caracteres`; renderQR(els.offerQr,code); els.offerArea.classList.remove('hidden'); }
async function receiveOffer(){ try{ const sig=await decodeSignal(els.offerInput.value); const peer=makePeer(); await peer.setRemoteDescription(sig); await peer.setLocalDescription(await peer.createAnswer()); await waitIce(peer); const code=await encodeSignal(peer.localDescription.toJSON()); els.answerCode.value=code; els.answerSize.textContent=`${code.length} caracteres`;renderQR(els.answerQr,code);els.answerArea.classList.remove('hidden');toast('Resposta criada'); }catch(e){toast(e.message||'Convite inválido');} }
async function applyAnswer(){ try{ const sig=await decodeSignal(els.answerInput.value); await pc.setRemoteDescription(sig); show(els.transfer);els.state.textContent='CONECTANDO';els.transferTitle.textContent='Estabelecendo canal direto…'; }catch(e){toast(e.message||'Resposta inválida');} }
function reset(){ try{channel?.close();pc?.close();}catch{} pc=channel=null;selectedFile=null;receiveMeta=null;receiveChunks=[];els.file.value='';els.dropTitle.textContent='Toque para escolher um arquivo';els.dropHint.textContent='ou arraste e solte aqui';els.offerArea.classList.add('hidden');els.answerArea.classList.add('hidden');els.offerInput.value=els.answerInput.value='';els.result.classList.add('hidden');updateTransfer(0,0);show(els.start); }
function chooseFile(file){ if(!file)return;selectedFile=file;els.dropTitle.textContent=file.name;els.dropHint.textContent=`${formatBytes(file.size)} · ${file.type||'tipo desconhecido'}`;createOffer(); }
async function scanInto(target){ if(!('BarcodeDetector' in window)||!navigator.mediaDevices?.getUserMedia){toast('Leitor de QR indisponível neste navegador');return;} try{const detector=new BarcodeDetector({formats:['qr_code']});scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});els.scannerVideo.srcObject=scannerStream;els.scanner.showModal();const loop=async()=>{try{const codes=await detector.detect(els.scannerVideo);if(codes[0]?.rawValue){target.value=codes[0].rawValue;closeScanner();toast('QR lido');return;}}catch{}scanTimer=requestAnimationFrame(loop)};loop();}catch{toast('Não foi possível abrir a câmera');} }
function closeScanner(){ cancelAnimationFrame(scanTimer);scannerStream?.getTracks().forEach(t=>t.stop());scannerStream=null;if(els.scanner.open)els.scanner.close(); }

$('#sendChoice').onclick=()=>show(els.send);$('#receiveChoice').onclick=()=>show(els.receive);els.file.onchange=e=>chooseFile(e.target.files[0]);els.drop.ondragover=e=>{e.preventDefault();els.drop.classList.add('drag')};els.drop.ondragleave=()=>els.drop.classList.remove('drag');els.drop.ondrop=e=>{e.preventDefault();els.drop.classList.remove('drag');chooseFile(e.dataTransfer.files[0]);};$('#acceptOffer').onclick=receiveOffer;$('#applyAnswer').onclick=applyAnswer;$('#scanOffer').onclick=()=>scanInto(els.offerInput);$('#scanAnswer').onclick=()=>scanInto(els.answerInput);$('#closeScanner').onclick=closeScanner;$$('[data-reset]').forEach(b=>b.onclick=reset);$$('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText($('#'+b.dataset.copy).value);toast('Código copiado');});window.addEventListener('beforeunload',()=>{try{pc?.close()}catch{}});
